project_id = "albeqixkyjdxinxbiuww"

[functions.generate-brand-text]
verify_jwt = false

[functions.generate-brand-image]
verify_jwt = false

[functions.generate-brand-chart]
verify_jwt = false

[functions.check-page-dependencies]
verify_jwt = false

[functions.transform-content]
verify_jwt = false

[functions.generate-case-study]
verify_jwt = false

[functions.generate-case-study-suggestions]
verify_jwt = false

[functions.generate-template]
verify_jwt = false

[functions.parse-document]
verify_jwt = true
